apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '30s', target: 50 },
        { duration: '1m', target: 100 },
        { duration: '30s', target: 200 },
        { duration: '1m', target: 300 },
        { duration: '30s', target: 0 },
      ],
    };

    export default function () {
      let response = http.get('http://webapp.default.svc.cluster.local/');
      check(response, {
        'status is 200': (r) => r.status === 200,
      });
      
      sleep(Math.random() * 2);
    }