apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443
          
          hostPort:
            enabled: true
            ports:
              http: 80
              https: 443
          
          nodeSelector:
            ingress-ready: "true"
          
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Equal
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Equal
            effect: NoSchedule
          
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
            use-proxy-protocol: "false"
          
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          
          admissionWebhooks:
            enabled: true
            patch:
              enabled: true
              image:
                repository: registry.k8s.io/ingress-nginx/kube-webhook-certgen
                tag: v20231011-8b53cabe0

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true