apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.9.0
    helm:
      values: |
        replicaCount: 2
        
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        
        service:
          type: ClusterIP
        
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: podinfo.local
              paths:
                - path: /
                  pathType: Prefix
        
        # Enable HPA
        hpa:
          enabled: true
          minReplicas: 2
          maxReplicas: 10
          targetCPUUtilizationPercentage: 70
          # Optional: target memory utilization
          # targetMemoryUtilizationPercentage: 80
        
        serviceMonitor:
          enabled: true
          interval: 15s
        
        redis:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true